blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion Forum
    url: https://discuss.px4.io/c/qgroundcontrol
    about: For general questions and discussions, please use our forum
  - name: ğŸ“– User Documentation
    url: https://docs.qgroundcontrol.com/
    about: Read the user manual for help with using QGroundControl
  - name: ğŸ› ï¸ Developer Documentation
    url: https://dev.qgroundcontrol.com/
    about: Read the developer guide for help building and contributing
  - name: ğŸ’» Discord Community
    url: https://discord.gg/dronecode
    about: Join our Discord server for real-time chat
