name: Crowdin - Upload Guide sources (en)

# https://github.com/crowdin/github-action/tree/master

on:
  push:
    branches:
      - master
    paths:
      - 'docs/en/**'
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - 'docs/en/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  upload-to-crowdin:
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Upload sources to Crowdin
        uses: crowdin/github-action@v2
        with:
          config: 'docs/crowdin_docs.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: master
        env:
          GITHUB_TOKEN: ${{ secrets.PX4BUILDBOT_ACCESSTOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_DOCS_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.PX4BUILDBOT_CROWDIN_PERSONAL_TOKEN }}
