name: Update Translations

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * 0'

concurrency:
  group: 'lupdate'
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-translations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Qt for Linux
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          cache: true

      - name: Update translation files
        run: |
          cd translations
          ${{ env.QT_ROOT_DIR }}/bin/lupdate ../src -ts qgc.ts -no-obsolete
          python3 qgc-lupdate-json.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated translations
        run: |
          git add translations/*.ts
          git diff --cached --quiet || git commit -m "Chore: Update Translations"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-translations-${{ github.run_id }}
          title: "chore: update translations"
          commit-message: "chore: update translations"
          body: |
            This PR was automatically generated by GitHub Actions to update the Qt `.ts` translation files.
